spring.application.name=ride-management-service
server.port=8083

spring.config.import=optional:file:.env[.properties]

# Spring Cloud OpenFeign
spring.cloud.compatibility-verifier.enabled=false

# Spring Data MongoDB Configuration
spring.data.mongodb.uri=${MONGO_URI:mongodb://localhost:27017/ridelink_ride_management_db}

# JWT Configuration
jwt.secret=${JWT_SECRET}

# Account Service URL
services.account-service.base-url=${ACCOUNT_SERVICE_URL:http://localhost:8081}

# Driver Service URL
services.driver-service.base-url=${DRIVER_SERVICE_URL:http://localhost:8082}

# Fare Payment Service URL (Member 4)
services.fare-payment-service.base-url=${FARE_PAYMENT_SERVICE_URL:http://localhost:8084}

# Springdoc / Swagger
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.operationsSorter=method

# Logging
logging.level.com.ridelink=DEBUG
logging.level.org.springframework.security=INFO
